'''1. Rolling Dice Simulator
Goal: Generate and display a random integer between 1 and 6 whenever the user presses Enter, until they type quit.'''
import random

rollTime = input('Press Enter to roll dice and to stop press quit: ')

while rollTime != "quit":
    if rollTime == "Enter" or rollTime == "enter":
        print(f"{random.randint(1,6)}\n{rollTime}")
        rollTime = input('Press Enter to roll dice and to stop press quit: ') #this is repetitive and not Pythonic, how can I shorten this?
    else:
        print(f"Invalid input. Please try again.\n{rollTime}")

'''
Wow! New lesson learned, combining loops with conditionals is great!
Instructions generated by Google Gemini©
Project coded by me
'''

'''
Google Gemini© Solution

import random

while True:
    rollTime = input('Press Enter to roll dice (or type "quit" to stop): ')
    
    if rollTime == "quit":
        break
    elif rollTime == "":  # User pressed Enter without typing anything
        print(f"You rolled: {random.randint(1, 6)}\n")
    else:
        print("Invalid input. Press Enter to roll or type 'quit'.\n")
'''

'''
MORE PYTHONIC OBSERVATIONS
-------------

1. while True = sets loop
2. "" means pressing Enter
3. input inside while loop so no need to paste jargon!

'''
